### ISSUE TITLE
Publish spring-web-rythm-template on a public maven repository

### ISSUE THREAD

**Issue by vanto** [LCTL/spring-webmvc-rythm#1]
Perhaps following the Rythm/Play-Rythm naming schema and calling the artifact springmvc-rythm to make it easier to discover.

That would be great!

**Comment by LCTL** [comment]
Just waiting Rythm Template Engine to publish on a public maven repository, because depend on it.

I suggest change artifact to `spring-webmvc-rythm`.

**Comment by vanto** [comment]
Thanks. At least a snapshot is already available: https://oss.sonatype.org/index.html#nexus-search;quick~rythm

**Comment by agibalov** [comment]
Lawrence, it's already 8 months since last update here - maybe you could host Maven artifacts right on github as a temporary solution? (http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github)

**Comment by LCTL** [comment]
I have been created the JIRA ticket on SonaType for publish this project to central maven. It may take a few days?

https://issues.sonatype.org/browse/OSSRH-7266

**Comment by LCTL** [comment]
I already publish to central Maven repository.

http://search.maven.org/#search%7Cga%7C1%7Cspring-webmvc-rythm

**Comment by agibalov** [comment]
Great news! Thanks a lot!
