### ISSUE TITLE
How to pass a object from spring-controller to rythm-template ?

### ISSUE THREAD

**Issue by magixsource** [LCTL/spring-webmvc-rythm#10]
In the Rythm offical website,pass a object can be this way:

Map<String, Object> params = new HashMap<String, Object>();
params.put("who", "world");
String s = Rythm.render("Hello @who", params);

and i use spring-web-rythm and in spring-controller-layer this way:

Map<String, Object> params = new HashMap<String, Object>();
params.put("@who", "SNAKE");
return Rythm.render("home", params);

but in the rythm-template is echo @who is null 

Could you point me ?

**Comment by LCTL** [comment]
You want to directly render the template?

Spring Web MVC controller should be:

```
@Controller
public class HelloWorldController {

    @RequestMapping("/helloWorld")
    public String helloWorld(Model model) {
        model.addAttribute("who", "SNAKE");

        //template file name
        return "helloWorld";
    }

}
```

helloWorld.html

```
@args String who

Hello @who
```

**Comment by magixsource** [comment]
hi,lawrence:
   It's work good now~
   THX ;-)
