### ISSUE TITLE
Tmp file not found

### ISSUE THREAD

**Issue by zhaopuming** [LCTL/spring-webmvc-rythm#11]
I set up a spring-rythm project as you described, but when I run a controller, at the first time, a FileNotFoundException occurred:

> java.io.FileNotFoundException: C:\Users\visus\AppData\Local\Temp__rythm\home_devel_workspaces_bazaro__metadata__plugins_org_eclipse_wst_server_core_tmp0_wtpwebapps_spring_rythm_WEB_INF_views_hello_html__R_T_C__.java (系统找不到指定的路径。)

then at the second refresh, another exception:

> java.io.FileNotFoundException: C:\Users\visus\AppData\Local\Temp__rythm\home_devel_workspaces_bazaro__metadata__plugins_org_eclipse_wst_server_core_tmp0_wtpwebapps_spring_rythm_WEB_INF_views_hello_html__R_T_C__.rythm (系统找不到指定的路径。)

Then at the third time, the page renders OK.

But when I change the template file and hit refresh, those exceptions occurred again,
and then only the first rendered pages shows. Future modification to the template shows no effect.

Can you give me a hint where I got it wrong?

**Comment by LCTL** [comment]
What version of spring-web-rythm-template are you running?

Would you mind provide the test project for debug?

**Comment by magixsource** [comment]
zhaopuming ,I think this  issue  Caused by Rythm ifself. you can new a folder like "C:\Users\visus\AppData\Local\Temp__rythm" 
HEiHEi
