### ISSUE TITLE
How to use variables stored in sesssion?

### ISSUE THREAD

**Issue by shuai-zh** [LCTL/spring-webmvc-rythm#17]
I stored the user info session after the user has signed in, however I cannot find any way to use the user info object in the rythm template. Can you give me a hint? I am using springmvc with rythm just as this demo.

Thanks.

**Comment by shuai-zh** [comment]
I managed to find a way to print session variables like following:

```
@request.getSession().getAttribute("currentUsername")
```

It's somehow ugly, do you have any better ways?

**Comment by LCTL** [comment]
You can create Tag object for print session variable in template.

Example: https://github.com/lawrence0819/spring-webmvc-rythm/blob/master/src/main/java/com/ctlok/springframework/web/servlet/view/rythm/tag/CookieValue.java

Add Tag object to RythmConfigurator:

```
<property name="tags">
    <list>
        <bean class="com.ctlok.springframework.web.servlet.view.rythm.tag.SessionValue" />
    </list>
</property>
```

**Comment by shuai-zh** [comment]
Got it, thanks.
