### ISSUE TITLE
problem with type resolution

### ISSUE THREAD

**Issue by ttux** [LCTL/spring-webmvc-rythm#3]
Hi,
I'm not sure it is related to the plugin or if it is something I don't do correctly. I am new with both this plugin and the rythm engine.

I have the following exception:
com.greenlaw110.rythm.exception.CompileException: Post cannot be resolved to a type

The template:

```
@for (Post p: posts) {
    <h2>@p.getTitle()</h2>
}
```

The java code:

``` java
@RequestMapping(value="/")
public String home(@RequestParam(required=false) Integer page, ModelMap model) {
    model.put("posts", postDAO.get(page==null ? 0 : page));
    return "home";
}
```

posts is a:

``` java
List<Post>
```

Am I supposed to add some import statement to the template?

Thank you for you help and for your work.

P.S:
There is a mistake in the readme for the maven dependency. It should be:

```
<artifactId>spring-webmvc-rythm</artifactId>
```

Currently it is:

```
<artifactId>spring-web-rythm-template</artifactId>
```

**Comment by ttux** [comment]
If I change my template like this then it works:

``` java
@args List<com.mypackage.domains.Post> posts;

@for (com.mypackage.domains.Post p: posts) {
    <h2>@p.getTitle()</h2>
}
```

But I obviously don't want to have to do this.

**Comment by ttux** [comment]
So at the end I went to look at RythmConfigurator.java and found out I could set implicitPackages so I added this to my rythmConfigurator bean:

``` xml
<property name="implicitPackages">
    <list>
        <value>com.mypackage.domains.*</value>
    </list>
</property>
```

**Comment by LCTL** [comment]
Sorry, I have not update the document for all provided config. 

Setup implicit packages config for Rythm template engine to import package to all generated java template file, but you must be care same object name when you using wildcard to import.

**Comment by grnt426** [comment]
Can you explain how to configure the "implicitPackages" property without the bean configuration? I am trying to configure by passing in Map objects. I searched through the documentation here: http://rythmengine.org/doc/configuration.md#engine but it does not explain how to configure or set the property mentioned above.

Here is how I am configuring it:
```java
Map<String, Object> map = new HashMap<>();
map.put(RythmConfigurationKey.HOME_TEMPLATE.getKey(), pathToTemplates);
Rythm.init(map);
```

**Comment by LCTL** [comment]
Are you directly init Rythm object from Java code instead of through Spring configuration?

You can view this method for reference: 
https://github.com/lawrence0819/spring-webmvc-rythm/blob/master/src/main/java/com/ctlok/springframework/web/servlet/view/rythm/RythmConfigurator.java#L106
