### ISSUE TITLE
A problem about preventing from using other viewResolver.

### ISSUE THREAD

**Issue by yeyanzhao** [LCTL/spring-webmvc-rythm#6]
Eh...~ Hi Lawrence!
I am sorry to disturb you again~
Since I can Intergrate the Spring-rythm in my own spring project, I find that if I assign the 
RythmViewResolver the first resolver, the other viewResolver will not work again even when the view is not rythm view. 
After some researching. I found that if add one method checkResource() to the RythmView to check whether the file exists, then the other view resolver will work normally.
The method is like following:
    @Override
    public boolean checkResource(Locale locale) throws Exception {
        File file = new File(this.getServletContext().getRealPath("/") + getUrl());
        return file.exists();
    }
So I think if you add this method to RythmView class, then this plugin will more fiendly to other view.

I don't if there were other better method to do this. Hope more discussion...

**Comment by LCTL** [comment]
I suggest config `org.springframework.web.servlet.view.ContentNegotiatingViewResolver` and set `mediaTypes` to specify view resolver. (e.g. `application/json` with `org.springframework.web.servlet.view.json.MappingJackson2JsonView`)

**Comment by yeyanzhao** [comment]
I combine the jsp and rythm together, and both of them are text/html type. 
Eh, I guess the ContentNegotiatingViewResolver used mainly in differentiating such as json, xml and text/html.
So I think it does not suit this situation. 
And I don't know why most of the UrlBasedViewResolver just using the "return true" to deal with this problem.
And maybe there will be another discussion about why combine jsp and rythm, why not just use one of them.
