### ISSUE TITLE
A problem about I18N

### ISSUE THREAD

**Issue by yeyanzhao** [LCTL/spring-webmvc-rythm#7]
eh, another question to consult..
I have two pages, one jsp and another rythm.html. 
They were respectively handled by InternalResourceViewResolver and RythmViewResolver. There were Chinese words in both of these two pages(the chinese words were placed in the pages directly). 
But just the jsp can be displayed correctly, and the rythm.html will show some ???????...
I don't have idea about why do this...
I guess it maybe relative to the extended RythmViewResolver or RythmView. 
But I am not sure...

**Comment by yeyanzhao** [comment]
This problem has been solved by add follow statement to the method renderMergedTemplateModel in RythmView class:
response.setCharacterEncoding(request.getCharacterEncoding());
And I think this may be just a simple solution for a moment. Maybe there were better one to do it.

**Comment by LCTL** [comment]
Please try:

```
<bean id="rythmViewResolver" class="com.ctlok.springframework.web.servlet.view.rythm.RythmViewResolver">
    <constructor-arg>
        <ref bean="rythmConfigurator" />
    </constructor-arg>
    <property name="contentType" value="text/html;charset=UTF-8" />
</bean>
```

**Comment by LCTL** [comment]
Work?

**Comment by yeyanzhao** [comment]
yes. it does work. Thx.
